name: Build and Release Firmware

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Adjust the tag pattern if necessary

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
      
    - name: Install PlatformIO
      run: pip install platformio
      
    - name: Build Firmware
      run: pio run
      
    - name: Archive Production Artifacts
      run: |
        zip -r firmware.zip .pio/build/*/firmware.bin
        mv firmware.zip firmware/
      working-directory: ${{ github.workspace }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: firmware/firmware.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download Firmware Artifact
      uses: actions/download-artifact@v4
      with:
        name: firmware
        path: firmware
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: firmware/firmware.zip
      env:
        GH_SECRET_TOKEN: ${{ secrets.GH_SECRET_TOKEN }}
